### ISSUE TITLE
Working with states that are not arrays.

### ISSUE THREAD

**Issue by felixchalumeau** [JuliaReinforcementLearning/ReinforcementLearningBase.jl#48]
Hi, 

Is it possible to work with states that are not arrays ? 

On one hand, they are a few indicators that show that other type than array are not welcome as state type. For instance:
- https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/master/src/interface.jl#L309 (documentation suggest that get_state(obs) should be an array. 
- But also the CircularCompactSARSATrajectory, which works with CircularArrayBuffer, which only works with arrays. 
- Finally, the implemented spaces do not suggest that states can have another type than an array.

But on the other hand, it seems that:
- an observation can perfectly work with a state having another type than Array 
- it also exists trajectories like VectorialCompactSARTSATrajectory, which give the possibility to use any type for the state. 
- finally, I don't really understand what are the state_spaces made for ? (or is it to help conversion when importing envs from other languages ? ) In any case, they do not seem to prevent the use of other types in the actual implementation.

All this make think that it might be possible to work with special type (other than Arrays). 

But I am yet trying to construct an experiment with state that are special types (to store specific graphs) and I am struggling to get my code finally work (I seem very close but still got issues). I know that I could express my special graph as an array but here let's assume that I won't.

That's why I would like to know if some parts of the code that I would have forget or misunderstood do prevent the use of special state types or is it possible (with a few efforts ;) ) to make it work !

PS: In case it is theorically possible to do it, I would be pleased to tell a bit more about the mistake that is preventing me to get my stuff working !

**Comment by findmyway** [comment]
Hi @felixchalumeau ,

First, I'd say that most of your understandings are correct!

> documentation suggest that get_state(obs) should be an array

Sorry that the doc is not updated. (I'll fix it soon) As you can see, `get_state(obs) = obs.state`. From the API level, it doesn't assume that `state` must be an array.

> But also the CircularCompactSARSATrajectory, which works with CircularArrayBuffer, which only works with arrays.

Yes, because `CircularCompactSARSATrajectory` relies on a pre-allocated array to store data in a **Compact** way. So if your `state` is not an Array, you may use `VectorialCompactSARTSATrajectory` or **define your own trajectory**.

> Finally, the implemented spaces do not suggest that states can have another type than an array.

That's only part of the truth. For example, in `DiscreteSpace`, elements can of arbitrary types. But yes, in most cases, `states` are assumed to be an array. 

> an observation can perfectly work with a state having another type than Array

✔️That's it is designed to be.

> it also exists trajectories like VectorialCompactSARTSATrajectory, which give the possibility to use any type for the state.

✔️But `VectorialCompactSARTSATrajectory` only exists for completeness. I've never used it for real problems. So use it with caution.

> finally, I don't really understand what are the state_spaces made for ? (or is it to help conversion when importing envs from other languages ? ) In any case, they do not seem to prevent the use of other types in the actual implementation.

✔️  state spaces are mostly adapt from OpenAI Gym.

> That's why I would like to know if some parts of the code that I would have forget or misunderstood do prevent the use of special state types or is it possible (with a few efforts ;) ) to make it work !

TBH, I haven't work on any problem with state of non-Array type. So you may need to get your hands dirty by defining some customized components.

1. Use `VectorialCompactSARTSATrajectory` or define your own trajectory. But I think `VectorialCompactSARTSATrajectory` is a good start point. Otherwise, beside implementing the AbstractTrajectory interfaces, you also need to implement when to update the trajectory, like this https://github.com/JuliaReinforcementLearning/ReinforcementLearningCore.jl/blob/master/src/components/agents/agent.jl#L179-L219
1. Since you are using non-Array states, most policies/learners in this package will not work. So you need to have your own policy implement:
  - `your_policy(obs) -> action`
  - `update!(your_policy, trajectory::VectorialCompactSARTSATrajectory)`

It would be easier for me to help you if you can provide more details (what kind of the specific graph is) or some example codes.
